import { ResumeData, Language } from './types';

export const UI_TRANSLATIONS = {
  about_me: { en: "About Me", no: "Om Meg", zh: "关于我" },
  linkedin_profile: { en: "LinkedIn Profile", no: "LinkedIn Profil", zh: "LinkedIn 个人资料" },
  global_footprint: { en: "Global Footprint", no: "Globalt Fotavtrykk", zh: "全球足迹" },
  map_legend_employment: { en: "Employment History", no: "Arbeidserfaring", zh: "工作经历" },
  map_legend_project: { en: "Project Experience", no: "Prosjekterfaring", zh: "项目经验" },
  map_legend_toggle: { en: "Click to toggle", no: "Klikk for å bytte", zh: "点击切换" },
  timeline: { en: "Career Timeline", no: "Karriere Tidslinje", zh: "职业生涯时间轴" },
  skills_languages: { en: "Skills & Languages", no: "Ferdigheter og Språk", zh: "技能与语言" },
  technical_skills: { en: "Technical Skills", no: "Tekniske Ferdigheter", zh: "技术技能" },
  languages: { en: "Languages", no: "Språk", zh: "语言" },
  certifications: { en: "Certifications", no: "Sertifiseringer", zh: "证书" },
  education: { en: "Education", no: "Utdanning", zh: "教育背景" },
  key_projects: { en: "Key Projects", no: "Nøkkelprosjekter", zh: "重点项目" },
  experience_history: { en: "Experience History", no: "Erfaringshistorikk", zh: "工作履历" },
  detailed_experience: { en: "Detailed Experience", no: "Detaljert Erfaring", zh: "详细经历" },
  footer_rights: { en: "All rights reserved.", no: "Alle rettigheter forbeholdt.", zh: "保留所有权利。" },
  footer_generated: { en: "Generated by AI Studio", no: "Generert av AI Studio", zh: "由 AI Studio 生成" },
  present: { en: "Present", no: "Nå", zh: "至今" },
  click_projects: { en: "Click to see projects", no: "Klikk for å se prosjekter", zh: "点击查看项目" },
  click_employment: { en: "Click to return to employment", no: "Klikk for å se arbeidserfaring", zh: "点击返回工作经历" }
};

export const RESUME_DATA: ResumeData = {
  contact: {
    name: "Reidar J. Boldevin",
    title: {
      en: "Principal Engineer | Cybersec & Identity Pragmatist",
      no: "Sjefingeniør | Cybersikkerhet og Identitetspragmatiker",
      zh: "首席工程师 | 网络安全与身份管理专家"
    },
    location: "Oslo, Norway",
    address: "Hofstadgata 7, 1384 Asker",
    email: "r_boldevin@hotmail.com",
    mobile: "+47 948 73 386",
    linkedin: "https://www.linkedin.com/in/rboldevin",
    bio: {
      en: "Cybersec and Identity Pragmatist | IT manager and public speaker | Full time worker, part time student.",
      no: "Cybersikkerhet og identitetspragmatiker | IT-leder og foredragsholder | Heltidsansatt, deltidsstudent.",
      zh: "网络安全与身份管理专家 | IT经理与演讲者 | 全职工作，兼职进修。"
    },
    summary: {
      en: "Consultant and leader who uses his 20+ years from the IT industry to create success. My range of experience stretches from support early on in my career, through operations and service management, to architecture and advisory. My primary technical skill is in the Microsoft space (Entra ID, Active Directory, Azure IaaS/PaaS/SaaS). I have experience working both in large enterprises and with smaller companies, working internationally as a consultant.",
      no: "Konsulent og leder som bruker sine 20+ år fra IT-bransjen til å skape suksess. Min erfaringsbakgrunn strekker seg fra support tidlig i karrieren, gjennom drift og tjenestestyring, til arkitektur og rådgivning. Min primære tekniske kompetanse er innen Microsoft-økosystemet (Entra ID, Active Directory, Azure IaaS/PaaS/SaaS). Jeg har erfaring med å jobbe både i store bedrifter og med mindre selskaper, og har jobbet internasjonalt som konsulent.",
      zh: "拥有20多年IT行业经验的顾问和领导者，致力于创造成功。我的经验涵盖从早期的技术支持，到运营和服务管理，再到架构设计和咨询。我的主要技术专长在微软领域（Entra ID, Active Directory, Azure IaaS/PaaS/SaaS）。我拥有在大型企业和小型公司工作的经验，并作为顾问在国际环境中工作。"
    }
  },
  skills: [
    "Cybersecurity",
    "Identity and Access Management (IAM)",
    "Microsoft Entra ID",
    "Active Directory",
    "Microsoft Azure (IaaS, PaaS, SaaS)",
    "Microsoft Defender & Sentinel",
    "Zero Trust Architecture",
    "IT Operations & Management",
    "Project Management",
    "Scrum Master / Agile"
  ],
  languages: [
    "Norwegian (Bokmål)",
    "English",
    "German"
  ],
  certifications: [
    { 
      name: "SC-100: Microsoft Cybersecurity Architect",
      description: {
        en: "Expert-level certification validating advanced skills in designing cybersecurity architectures, Zero Trust strategies, and governance for cloud and hybrid environments.",
        no: "Ekspert-nivå sertifisering som validerer avanserte ferdigheter i å designe cybersikkerhetsarkitekturer, Zero Trust-strategier og styring for sky- og hybridmiljøer.",
        zh: "专家级认证，验证在设计网络安全架构、零信任策略以及云和混合环境治理方面的高级技能。"
      }
    },
    { 
      name: "Microsoft Certified: Identity and Access Administrator Associate",
      description: {
        en: "Validates core skills in managing Entra ID (Azure AD), authentication, access control, and identity governance to secure organizational access.",
        no: "Validerer kjerneferdigheter i administrasjon av Entra ID (Azure AD), autentisering, tilgangskontroll og identitetsstyring for å sikre organisatorisk tilgang.",
        zh: "验证管理 Entra ID (Azure AD)、身份验证、访问控制和身份治理以确组织访问安全的核心技能。"
      }
    },
    { 
      name: "Microsoft Certified: Azure Fundamentals",
      description: {
        en: "Demonstrates foundational knowledge of cloud services, Azure workloads, security, privacy, pricing, and support, proving cloud fluency.",
        no: "Demonstrerer grunnleggende kunnskap om skytjenester, Azure-arbeidsbelastninger, sikkerhet, personvern, prising og support.",
        zh: "展示云服务、Azure 工作负载、安全性、隐私、定价和支持的基础知识，证明云流利度。"
      }
    },
    { 
      name: "Active Directory Risk Assessment as a Service",
      description: {
        en: "Specialized training in analyzing and mitigating security risks within Active Directory environments to ensure directory integrity and operational stability.",
        no: "Spesialisert opplæring i å analysere og redusere sikkerhetsrisikoer i Active Directory-miljøer for å sikre katalogintegritet og driftsstabilitet.",
        zh: "专门的培训，旨在分析和缓解 Active Directory 环境中的安全风险，以确保目录完整性和运行稳定性。"
      }
    },
    { 
      name: "Installing and Configuring Windows Server 2012",
      description: {
        en: "Technical competency in installing, configuring, and managing Windows Server 2012 infrastructure, including AD DS, DNS, and Group Policy management.",
        no: "Teknisk kompetanse i installasjon, konfigurasjon og administrasjon av Windows Server 2012-infrastruktur, inkludert AD DS, DNS og Group Policy-administrasjon.",
        zh: "安装、配置和管理 Windows Server 2012 基础设施（包括 AD DS、DNS 和组策略管理）的技术能力。"
      }
    }
  ],
  education: [
    {
      institution: "BI Norwegian Business School",
      degree: {
        en: "Executive Master of Management (105 ECTS)",
        no: "Executive Master of Management (105 studiepoeng)",
        zh: "行政管理硕士 (105 ECTS)"
      },
      period: "2020 - 2025",
      description: {
        en: "• Governance, Risk, Compliance and Internal Auditing (Spring 2025) - Grade A\n• Strategic Business Development and Innovation (Spring 2024) - Grade A\n• Leading in Digitized Workplaces (Spring 2023) - Grade A\n• Basic Business Economics (Spring 2021) - Grade A\n• Human Resource Management (Spring 2021) - Grade C\n• Logistics and Marketing (Autumn 2020) - Grade B\n• Leadership. Theory and Practice (Autumn 2020) - Grade C",
        no: "• Styring, Risikostyring, Etterlevelse og Internrevisjon (Vår 2025) - Karakter A\n• Strategisk Forretningsutvikling og Innovasjon (Vår 2024) - Karakter A\n• Ledelse i Digitaliserte Arbeidsplasser (Vår 2023) - Karakter A\n• Bedriftsøkonomi (Vår 2021) - Karakter A\n• Human Resource Management (Vår 2021) - Karakter C\n• Logistikk og Markedsføring (Høst 2020) - Karakter B\n• Ledelse. Teori og Praksis (Høst 2020) - Karakter C",
        zh: "• 治理、风险管理、合规与内部审计 (2025春) - 成绩 A\n• 战略业务发展与创新 (2024春) - 成绩 A\n• 数字化工作场所领导力 (2023春) - 成绩 A\n• 基础商业经济学 (2021春) - 成绩 A\n• 人力资源管理 (2021春) - 成绩 C\n• 物流与市场营销 (2020秋) - 成绩 B\n• 领导力：理论与实践 (2020秋) - 成绩 C"
      }
    },
    {
      institution: "University of Stavanger",
      degree: {
        en: "Financial & Management Studies (25 ECTS)",
        no: "Økonomi og Ledelsesstudier (25 studiepoeng)",
        zh: "财务与管理研究 (25 ECTS)"
      },
      period: "2021 - 2022",
      description: {
        en: "• Financial accounting - Analysis and reporting (Autumn 2022) - Grade A\n• Cyber Security (Autumn 2022) - Grade B\n• Business decision making (Autumn 2022) - Grade B\n• Financial Management – budgeting and forecasting (Autumn 2021) - Grade B\n• Introduction to Management of health, safety and environment (Spring 2021) - Grade A",
        no: "• Finansregnskap - Analyse og rapportering (Høst 2022) - Karakter A\n• Cybersikkerhet (Høst 2022) - Karakter B\n• Økonomiske beslutningsproblemer (Høst 2022) - Karakter B\n• Økonomistyring – budsjettering og prognoser (Høst 2021) - Karakter B\n• Innføring i Helse, Miljø og Sikkerhet (Vår 2021) - Karakter A",
        zh: "• 财务会计 - 分析与报告 (2022秋) - 成绩 A\n• 网络安全 (2022秋) - 成绩 B\n• 商业决策 (2022秋) - 成绩 B\n• 财务管理 – 预算与预测 (2021秋) - 成绩 B\n• 健康、安全与环境管理导论 (2021春) - 成绩 A"
      }
    },
    {
      institution: "Kristiania University of Applied Sciences",
      degree: {
        en: "Vocational & Applied Management",
        no: "Fagskoleutdanning & Ledelse",
        zh: "职业与应用管理"
      },
      period: "2021 - 2022",
      description: {
        en: "• Project Management in Practice (Spring 2022) - Grade C\n• Change Management (Autumn 2021) - Grade C",
        no: "• Prosjektledelse i praksis (Vår 2022) - Karakter C\n• Endringsledelse (Høst 2021) - Karakter C",
        zh: "• 项目管理实践 (2022春) - 成绩 C\n• 变革管理 (2021秋) - 成绩 C"
      }
    },
    {
      institution: "University of South-Eastern Norway",
      degree: {
        en: "Information Systems",
        no: "Informasjonssystemer",
        zh: "信息系统"
      },
      period: "2020",
      description: {
        en: "• Information Systems (Autumn 2020) - Grade B",
        no: "• Informasjonssystemer (Høst 2020) - Karakter B",
        zh: "• 信息系统 (2020秋) - 成绩 B"
      }
    }
  ],
  employmentHistory: [
    {
      company: "Fortytwo",
      role: {
        en: "Principal Engineer",
        no: "Sjefingeniør",
        zh: "首席工程师"
      },
      startDate: "2025-10-01",
      endDate: "Present",
      location: "Oslo, Norway",
      lat: 59.9139,
      lng: 10.7522,
      description: {
        en: "Working to improve myself also means I'm positioned to accept new challenges that would otherwise have been out of reach.",
        no: "Å jobbe med å forbedre meg selv betyr også at jeg er posisjonert til å ta på meg nye utfordringer som ellers ville vært utenfor rekkevidde.",
        zh: "努力提升自己也意味着我有能力接受那些本来遥不可及的新挑战。"
      }
    },
    {
      company: "Columbus",
      role: {
        en: "Consulting Manager - Cyber Security",
        no: "Consulting Manager - Cybersikkerhet",
        zh: "咨询经理 - 网络安全"
      },
      startDate: "2023-12-01",
      endDate: "2025-10-01",
      location: "Oslo, Norway",
      lat: 59.9139,
      lng: 10.7522,
      description: {
        en: "Helping clients keep core business running by securing what is important. Core business is Cyber Security.",
        no: "Hjelper kunder med å holde kjernevirksomheten i gang ved å sikre det som er viktig. Kjernevirksomheten er cybersikkerhet.",
        zh: "通过保护重要资产帮助客户维持核心业务运行。核心业务是网络安全。"
      }
    },
    {
      company: "PwC Norway",
      role: {
        en: "Senior Manager",
        no: "Senior Manager",
        zh: "高级经理"
      },
      startDate: "2022-04-01",
      endDate: "2023-12-01",
      location: "Oslo, Norway",
      lat: 59.9139,
      lng: 10.7522,
      description: {
        en: "Cyber & Privacy Senior Manager.",
        no: "Senior Manager innen Cyber & Privacy.",
        zh: "网络与隐私高级经理。"
      }
    },
    {
      company: "Innovation Norway",
      role: {
        en: "Special Advisor - IAM",
        no: "Spesialrådgiver - IAM",
        zh: "特约顾问 - IAM"
      },
      startDate: "2019-08-01",
      endDate: "2022-04-01",
      location: "Oslo Area, Norway",
      lat: 59.9139,
      lng: 10.7522,
      description: {
        en: "Team lead/Scrum Master IT Workplace. Tech lead IAM. SecOps. Solution architect (workplace/endpoint management). General cloud operations.",
        no: "Teamleder/Scrum Master IT Workplace. Teknisk leder IAM. SecOps. Løsningsarkitekt (arbeidsplass/klienthåndtering). Generell skydrift.",
        zh: "IT工作场所团队负责人/Scrum Master。IAM技术负责人。SecOps。解决方案架构师（工作场所/终端管理）。通用云运营。"
      }
    },
    {
      company: "FLIR Systems",
      role: {
        en: "Global Identity Technical Lead",
        no: "Global Identity Technical Lead",
        zh: "全球身份技术负责人"
      },
      startDate: "2016-12-01",
      endDate: "2019-07-01",
      location: "Hvalstad, Norway",
      lat: 59.8596,
      lng: 10.4939,
      description: {
        en: "Day to day management of IT operations with primary focus on Azure Cloud solutions and Identity Management. Tasks: IT planning, roadmap design, Azure AD architecture, AD security, etc.",
        no: "Daglig ledelse av IT-drift med hovedfokus på Azure Cloud-løsninger og identitetsstyring. Oppgaver: IT-planlegging, veikartdesign, Azure AD-arkitektur, AD-sikkerhet, osv.",
        zh: "负责IT运营的日常管理，主要关注Azure云解决方案和身份管理。任务：IT规划，路线图设计，Azure AD架构，AD安全等。"
      }
    },
    {
      company: "Microsoft",
      role: {
        en: "Sr. Premier Field Engineer",
        no: "Sr. Premier Field Engineer",
        zh: "高级 Premier Field Engineer"
      },
      startDate: "2014-10-01",
      endDate: "2016-11-01",
      location: "Oslo Area, Norway",
      lat: 59.9139,
      lng: 10.7522,
      description: {
        en: "Active Directory and Windows Server specialist working pro-actively and reactively with Microsoft's Premier clients. Workshops and trainings.",
        no: "Spesialist på Active Directory og Windows Server som jobber proaktivt og reaktivt med Microsofts Premier-kunder. Workshops og opplæring.",
        zh: "Active Directory和Windows Server专家，积极响应并服务于微软的Premier客户。提供研讨会和培训。"
      }
    },
    {
      company: "HV-02 Innsatsstyrke Derby",
      role: {
        en: "Ranger",
        no: "Jeger og skarpskytter",
        zh: "特种兵"
      },
      startDate: "2014-01-01",
      endDate: "2022-05-01",
      location: "Oslo, Norway",
      lat: 59.9139,
      lng: 10.7522,
      description: {
        en: "Scout, Patrol medic, Weapons operator. Gathering intelligence through search, disclosure and surveillance.",
        no: "Speider, patruljesanitet, våpenoperatør. Innhenting av etterretning gjennom søk, oppklaring og overvåking.",
        zh: "侦察兵，巡逻医务兵，武器操作员。通过搜索、揭露和监视收集情报。"
      }
    },
    {
      company: "Move AS",
      role: {
        en: "Senior Consultant",
        no: "Senior Konsulent",
        zh: "高级顾问"
      },
      startDate: "2013-08-01",
      endDate: "2014-09-01",
      location: "Oslo, Norway",
      lat: 59.9139,
      lng: 10.7522
    },
    {
      company: "Crayon",
      role: {
        en: "Consultant",
        no: "Konsulent",
        zh: "顾问"
      },
      startDate: "2011-02-01",
      endDate: "2013-07-01",
      location: "Oslo, Norway",
      lat: 59.9139,
      lng: 10.7522,
      description: {
        en: "Consultant managing complex Windows infrastructure environments, including VMWare, Citrix and Exchange.",
        no: "Konsulent som administrerer komplekse Windows-infrastrukturmiljøer, inkludert VMWare, Citrix og Exchange.",
        zh: "管理复杂Windows基础设施环境的顾问，包括VMWare，Citrix和Exchange。"
      }
    },
    {
      company: "Advent Software",
      role: {
        en: "Technical Implementation Consultant",
        no: "Teknisk Implementeringskonsulent",
        zh: "技术实施顾问"
      },
      startDate: "2008-07-01",
      endDate: "2010-12-01",
      location: "Oslo, Norway",
      lat: 59.9139,
      lng: 10.7522,
      description: {
        en: "Part of Advent's Consulting Team. Assisting investment professionals in implementing and using Advent’s products.",
        no: "En del av Advents Consulting Team. Bisto investeringsfagfolk med å implementere og bruke Advents produkter.",
        zh: "Advent咨询团队成员。协助投资专业人士实施和使用Advent的产品。"
      }
    },
    {
      company: "Advent Software",
      role: {
        en: "Support Consultant",
        no: "Supportkonsulent",
        zh: "支持顾问"
      },
      startDate: "2006-06-01",
      endDate: "2008-06-01",
      location: "Oslo, Norway",
      lat: 59.9139,
      lng: 10.7522,
      description: {
        en: "Technical and functional support on Advent solutions for the financial industry.",
        no: "Teknisk og funksjonell support på Advent-løsninger for finansbransjen.",
        zh: "为金融行业提供Advent解决方案的技术和功能支持。"
      }
    },
    {
      company: "Grønland og Boldevin IT-service DA",
      role: {
        en: "Managing Director / Tech Consultant",
        no: "Daglig leder / Teknisk konsulent",
        zh: "总经理 / 技术顾问"
      },
      startDate: "2002-04-01",
      endDate: "2006-05-01",
      location: "Bergen, Norway",
      lat: 60.3913,
      lng: 5.3221,
      description: {
        en: "Installation of networks and servers. Troubleshooting hardware. Maintenance of web pages.",
        no: "Installasjon av nettverk og servere. Feilsøking av maskinvare. Vedlikehold av nettsider.",
        zh: "网络和服务器的安装。硬件故障排除。网页维护。"
      }
    },
    {
      company: "Infosys AS",
      role: {
        en: "Technical Consultant",
        no: "Teknisk Konsulent",
        zh: "技术顾问"
      },
      startDate: "2004-01-01",
      endDate: "2005-05-01",
      location: "Bergen, Norway",
      lat: 60.3913,
      lng: 5.3221,
      description: {
        en: "Installation and maintenance of Infosys logistics solution.",
        no: "Installasjon og vedlikehold av Infosys logistikkløsning.",
        zh: "Infosys物流解决方案的安装和维护。"
      }
    },
    {
      company: "ITpro.no AS",
      role: {
        en: "Editor / Journalist",
        no: "Redaktør / Journalist",
        zh: "编辑 / 记者"
      },
      startDate: "2003-10-01",
      endDate: "2004-10-01",
      location: "Bergen, Norway",
      lat: 60.3913,
      lng: 5.3221,
      description: {
        en: "Editorial responsibility for reviews of literature. Writing articles on hardware and events.",
        no: "Redaksjonelt ansvar for litteraturanmeldelser. Skriving av artikler om maskinvare og arrangementer.",
        zh: "负责文学评论的编辑工作。撰写关于硬件和事件的文章。"
      }
    },
    {
      company: "EDS",
      role: {
        en: "Helpdesk Coordinator Associate",
        no: "Helpdesk Coordinator Associate",
        zh: "服务台协调助理"
      },
      startDate: "2001-06-01",
      endDate: "2002-02-01",
      location: "Mechelen, Belgium",
      lat: 51.0259,
      lng: 4.477,
      description: {
        en: "End user support on standard Microsoft products, AS/400 and S/390 systems.",
        no: "Sluttbrukersupport på standard Microsoft-produkter, AS/400 og S/390-systemer.",
        zh: "标准微软产品、AS/400和S/390系统的最终用户支持。"
      }
    },
    {
      company: "Forsvaret - Norwegian Armed Forces",
      role: {
        en: "Team Leader / Guard Commander",
        no: "Lagfører / Vaktkommandør",
        zh: "班长 / 警卫指挥官"
      },
      startDate: "1999-06-01",
      endDate: "1999-12-01",
      location: "Andøya, Norway",
      lat: 69.3143,
      lng: 16.1205,
      description: {
        en: "Responsible for a guard team of soldiers.",
        no: "Ansvarlig for et vaktlag med soldater.",
        zh: "负责士兵警卫队。"
      }
    }
  ],
  projects: [
    {
      "name": "Bang & Olufsen - Dynamics F&O",
      "year": "2024",
      "description": {
        en: "Implementation of Microsoft Dynamics F&O. Responsible for development and architecture related to automation and self-service solutions for access management (Entra ID).",
        no: "Implementering av Microsoft Dynamics F&O. Ansvarlig for utvikling og arkitektur knyttet til automatisering og selvbetjente løsninger for tilgangsstyring (Entra ID).",
        zh: "实施 Microsoft Dynamics F&O。负责与访问管理（Entra ID）自动化和自助服务解决方案相关的开发和架构。"
      },
      "location": "Struer, Denmark",
      "lat": 56.4896,
      "lng": 8.5898
    },
    {
      "name": "LEGO Group - Access Management",
      "year": "2024",
      "description": {
        en: "Consulting, focusing on the use of Microsoft tools. Development of new concepts for access management.",
        no: "Rådgivning, med fokus på bruk av Microsoft-verktøy. Utarbeidelse av nye konsepter for tilgangsstyring.",
        zh: "咨询，专注于微软工具的使用。开发访问管理的新概念。"
      },
      "location": "Billund, Denmark",
      "lat": 55.7315,
      "lng": 9.1156
    },
    {
      "name": "Norsk Hydro - Security Response",
      "year": "2022 - 2023",
      "description": {
        en: "Assessment of security measures following a ransomware attack. Project manager for sub-projects.",
        no: "Vurdering av sikkerhetstiltak etter løsepengeangrep. Prosjektleder for delprosjekter.",
        zh: "勒索软件攻击后的安全措施评估。子项目经理。"
      },
      "location": "Oslo, Norway",
      "lat": 59.9196,
      "lng": 10.6651
    },
    {
      "name": "Unntatt offentligheten (Defense Sector SOC)",
      "year": "2022 - 2023",
      "description": {
        en: "Consulting on the procurement of SOC services for a customer in the defense sector.",
        no: "Rådgivning ved anskaffelse av SOC tjenester for kunde i forsvarssektoren.",
        zh: "为国防部门客户采购SOC服务提供咨询。"
      },
      "location": "Oslo, Norway",
      "lat": 59.9139,
      "lng": 10.7522
    },
    {
      "name": "CEPI - IAM Strategy",
      "year": "2022",
      "description": {
        en: "Assessment of IAM and security solutions, contribution to IT strategy.",
        no: "Vurdering av IAM- og sikkerhetsløsninger, bidrag til IT-strategi.",
        zh: "评估IAM和安全解决方案，为IT战略做出贡献。"
      },
      "location": "Oslo, Norway",
      "lat": 59.9320,
      "lng": 10.7680
    },
    {
      "name": "Norsk Rikskringkasting (NRK)",
      "year": "2022",
      "description": {
        en: "Daily operations and improvement initiatives within IT security.",
        no: "Daglig drift og forbedringsinitiativer innen IT-sikkerhet.",
        zh: "IT安全内的日常运营和改进计划。"
      },
      "location": "Oslo, Norway",
      "lat": 59.9345,
      "lng": 10.7183
    },
    {
      "name": "Mentor Medier - DPIA",
      "year": "2021",
      "description": {
        en: "DPIA for media units. Project management and coordination.",
        no: "DPIA for medieenheter. Prosjektledelse og koordinering.",
        zh: "媒体单位的DPIA。项目管理和协调。"
      },
      "location": "Oslo, Norway",
      "lat": 59.9160,
      "lng": 10.7400
    },
    {
      "name": "Innovation Norway - MFA Rollout",
      "year": "2019 - 2020",
      "description": {
        en: "Implementation of mandatory MFA throughout Innovation Norway.",
        no: "Implementering av obligatorisk MFA i hele Innovasjon Norge.",
        zh: "在整个挪威创新署实施强制性MFA。"
      },
      "location": "Oslo, Norway",
      "lat": 59.9125,
      "lng": 10.7423
    },
    {
      "name": "FLIR Systems - Pen Test Support",
      "year": "2017",
      "description": {
        en: "Advisor and operator in identity security during penetration tests.",
        no: "Rådgiver og operatør innen identitetssikkerhet under penetrasjonstester.",
        zh: "渗透测试期间的身份安全顾问和操作员。"
      },
      "location": "North Billerica, MA",
      "lat": 42.5636,
      "lng": -71.2638,
    },
    {
      "name": "Microsoft - Azure Training",
      "year": "2015 - 2016",
      "description": {
        en: "Instructor on Azure cloud services for several companies across Europe.",
        no: "Instruktør på Azure skytjenester for flere selskaper på tvers av Europa.",
        zh: "为欧洲多家公司提供Azure云服务的讲师。"
      },
      "location": "Oslo, Norway",
      "lat": 59.9075,
      "lng": 10.7593
    },
    {
      "name": "Norwegian Airshuttle - Hybrid Identity",
      "year": "2014 - 2016",
      "description": {
        en: "Primary contact for Norwegian Airshuttle on hybrid identity services.",
        no: "Primær kontakt for Norwegian Airshuttle på hybride identitetsjenester.",
        zh: "挪威航空混合身份服务的主要联系人。"
      },
      "location": "Fornebu, Norway",
      "lat": 59.8970,
      "lng": 10.6234
    },
    {
      "name": "Arab National Bank - System Upgrade",
      "year": "2009 - 2010",
      "description": {
        en: "Responsible for local upgrade of Advent Axys Portfolio Management System in Riyadh, Saudi Arabia.",
        no: "Ansvarlig for lokal oppgradering av Advent Axys Portfolio Management System i Riyadh, Saudi-Arabia.",
        zh: "负责沙特阿拉伯利雅得Advent Axys投资组合管理系统的本地升级。"
      },
      "location": "Riyadh, Saudi Arabia",
      "lat": 24.7136,
      "lng": 46.6753
    },
    {
      "name": "Qatari financial customer - Tamale RMS implementation",
      "year": "2009 - 2010",
      "description": {
        en: "Responsible for local upgrade of Advent Axys Portfolio Management System in Riyadh, Saudi Arabia.",
        no: "Ansvarlig for lokal oppgradering av Advent Axys Portfolio Management System i Riyadh, Saudi-Arabia.",
        zh: "负责沙特阿拉伯利雅得Advent Axys投资组合管理系统的本地升级。"
      },
      location: "Doha, Qatar",
      lat: 25.2854,
      lng: 51.5310,
    }
  ]
};

export const SYSTEM_INSTRUCTION = `You are the interactive portfolio assistant for Reidar J. Boldevin. Your goal is to highlight his expertise in Identity Security (Entra ID), Cloud Architecture (Azure), and IT Management.

**Guidelines:**
1. **Source of Truth:** Answer strictly based on the provided context (Employment History and Project Data). Do not fabricate details.
2. **Language:** Detect the language of the user's question. If asked in Norwegian, translate the context and answer in Norwegian. If English, answer in English.
3. **Specifics:** When asked about projects (e.g., LEGO, Hydro, Bang & Olufsen), explicitly cite the location, year, and specific technologies used (e.g., "In 2024 at LEGO Group in Billund...").
4. **Contextualizing:** If asked about a general technical concept (e.g., "What is Zero Trust?"), explain it specifically through the lens of how Reidar applied it in his projects.
5. **Contact:** If the user expresses interest in hiring or collaboration, clearly provide his email (reidar.boldevin@outlook.com) and LinkedIn profile.
`;